services:
  test-container1:
    image: ${IMAGE}:${TAG}
    container_name: test_container1
    network_mode: host
    volumes:
      - ./src:${WORKSPACE}/src:rw
      - build:${WORKSPACE}
      - /dev/input:/dev/input
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    environment:
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.X11-unix
    command: ros2 launch robot_description display2.launch.py
    tty: true
    stdin_open: true

volumes:
  build: 