/pointcloud2_assembler:
  ros__parameters:
    scan_topics:
      - /lidar/velodyne/front/cloud
      - /lidar/velodyne/rear/cloud
      - /lidar_localisation/front/cloud
      - /lidar_localisation/rear/cloud
      - /lidar_safety/front_right/cloud
      - /lidar_safety/front_left/cloud
      - /lidar_safety/rear_right/cloud
      - /lidar_safety/rear_left/cloud
    base_frame: imu_link
    frequency: 10

/p2l_node:
  ros__parameters:
    target_frame: base_link
    min_height: 0.0
    max_height: 3.0
    angle_min: -3.14159
    angle_max: 3.14159
    angle_increment: 0.0057 #0.0087
    scan_time: 0.1
    range_min: 0.5
    range_max: 75.0
    use_inf: true
    inf_epsilon: 1.0